### ISSUE TITLE
Todo!

### ISSUE THREAD

**Issue by MillenniumForce** [MillenniumForce/Hackathon-2arabs-and-Julian#1]
- [x] Create an interface for doctors on the server-side

- [x] Appointments Feature

- [x] CSV sheet read by python containing basic info about patients

- [x] Explain functionality in README file 

- [x] Add comments to all code explaining functionality, bugs, improvements etc.

- [x] Bug Testing Done

- [x] Video Presentation

- [x] Delete row fix
